"""Builds ../README.md. Every custom visual is emitted as a <picture> with dark + light sources,
which GitHub swaps according to the viewer's GitHub theme."""
from pathlib import Path

RAW = "https://raw.githubusercontent.com/ziadmomen10/ziadmomen10/main/assets/"


def pic(name, alt, href=None, width="100%"):
    if name.startswith("h-"):  # section titles have a light variant; everything else is one dark design
        tag = (f'<picture><source media="(prefers-color-scheme: dark)" srcset="{RAW}{name}.svg" />'
               f'<source media="(prefers-color-scheme: light)" srcset="{RAW}{name}-light.svg" />'
               f'<img width="{width}" src="{RAW}{name}.svg" alt="{alt}" /></picture>')
    else:
        tag = f'<img width="{width}" src="{RAW}{name}.svg" alt="{alt}" />'
    return f'<a href="{href}">{tag}</a>' if href else tag


def ext_pic(dark, light, alt, extra=""):
    return (f'<picture><source media="(prefers-color-scheme: dark)" srcset="{dark}" />'
            f'<source media="(prefers-color-scheme: light)" srcset="{light}" />'
            f'<img {extra} src="{dark}" alt="{alt}" /></picture>')


DIV = pic("divider", "")
ZAUDE = "https://github.com/ziadmomen10/zaude"
TYPING = ("https://readme-typing-svg.demolab.com?font=Fira+Code&weight=600&size=22&duration=3000&pause=1000&color={c}"
          "&center=true&vCenter=true&repeat=true&random=false&width=640&height=45"
          "&lines=Don't+vibe+code.+Zaude+code.;Director+of+Product+%26+Engineering;"
          "Shipped+%3D+green+build+%2B+0+critical+%2B+live+verified;TypeScript+%C2%B7+React+%C2%B7+Supabase+%C2%B7+Docker+%C2%B7+Python")
STREAK = ("https://streak-stats.demolab.com/?user=ziadmomen10&theme={t}&hide_border=true&background={bg}"
          "&ring={ring}&fire=a371f7&currStreakLabel={ring}")

md = f"""<!-- Generated by assets/_readme.py — visuals by assets/_generate_v3.py (pure CSS/SMIL SVG, one design for both themes). -->

<div align="center">

{pic("hero", "Ziad Momen — Director of Product and Engineering at UltaHost, Creator of Zaude", "https://github.com/ziadmomen10")}

<a href="{ZAUDE}"><img src="{TYPING.format(c="58A6FF")}" alt="Typing SVG" /></a>

<a href="{ZAUDE}"><img src="https://custom-icon-badges.demolab.com/badge/Creator_of-Zaude™-58a6ff?style=for-the-badge&logo=rocket&logoColor=white&labelColor=161b22" /></a>&nbsp;
<a href="https://github.com/Ulta-Host"><img src="https://custom-icon-badges.demolab.com/badge/UltaHost-Director_of_Product_%26_Eng-a371f7?style=for-the-badge&logo=organization&logoColor=white&labelColor=161b22" /></a>&nbsp;
<a href="https://github.com/ziadmomen10?tab=followers"><img src="https://custom-icon-badges.demolab.com/github/followers/ziadmomen10?style=for-the-badge&color=0d1117&labelColor=161b22&logo=person-add&logoColor=58a6ff&label=Followers" /></a>&nbsp;
<img src="https://komarev.com/ghpvc/?username=ziadmomen10&style=for-the-badge&color=0d1117&label=VISITORS&abbreviated=true" />&nbsp;
<a href="mailto:ziadmomen10@gmail.com"><img src="https://custom-icon-badges.demolab.com/badge/Let's_Talk-58a6ff?style=for-the-badge&logo=mail&logoColor=white" /></a>

</div>

{DIV}

{pic("h-about", "About Me")}

I'm the **Director of Product & Engineering at [UltaHost](https://ultahost.com)** in Egypt. I own products from the first data model to the production server: I set direction, design the systems, ship them and run them. I lead AI agents as an engineering team that has to **prove** its work: a green build with a real exit code, a multi-model review with zero critical or high findings, and a check of the live app.

{pic("about", "ziad.ts — role: Director of Product and Engineering at UltaHost, Egypt. Shipping Zaude, AI Hosting Assistant, Supabase Platform, CommunityOS. In production: AtomOS, AI Product UI.")}

{DIV}

{pic("h-ultahost", "At UltaHost")}

<table>
<tr>
<td width="150" align="center" valign="middle">
<a href="https://github.com/Ulta-Host"><img src="https://github.com/Ulta-Host.png?size=200" width="110" alt="UltaHost" /></a>
<br/><b><a href="https://ultahost.com">UltaHost</a></b>
<br/><sub>Director of Product &amp; Engineering</sub>
</td>
<td valign="middle">

I lead product and engineering across UltaHost's org: direction, architecture, delivery and production operations. Most of that code is private, so this is what's behind it.

<sub>Counted from default branches of the Ulta-Host org repos, October 2026.</sub>

</td>
</tr>
</table>

{pic("ultahost-stats", "UltaHost footprint: 1,750+ commits, 23 repositories, 6,085 CI tests, 129 API operations", "https://github.com/Ulta-Host")}

{pic("ultahost-areas", "UltaHost work areas: AI Hosting Assistant, Hosting Platform, DevOps and Monitoring, Internal Tools")}

{DIV}

{pic("h-zaude", "Flagship — Zaude", ZAUDE)}

<div align="center">

### *Don't vibe code. Zaude code.*

**An autonomous, self-governing layer on top of Claude Code, built for people who ship to production.**<br/>
Small stdlib-only Python kernel · never calls an API · MIT

</div>

{pic("zaude-terminal", "Animated Zaude session: a plain-language request routed through plan, build, test, a 5-model review panel, verification and a signed release", ZAUDE)}

{pic("zaude-features", "Zaude features: persistent memory, signed lifecycle, intent routing, 5-model review panel", ZAUDE)}

<div align="center">

<a href="{ZAUDE}"><img src="https://img.shields.io/badge/kernel_tests-284_passing-3fb950?style=for-the-badge&labelColor=161b22" /></a>
<a href="{ZAUDE}"><img src="https://img.shields.io/github/stars/ziadmomen10/zaude?style=for-the-badge&logo=github&color=58a6ff&labelColor=161b22" /></a>
<a href="{ZAUDE}/blob/main/GUIDE.md"><img src="https://img.shields.io/badge/read-the_guide-a371f7?style=for-the-badge&labelColor=161b22" /></a>

</div>

{DIV}

{pic("h-shiplog", "2026 Ship Log")}

{pic("shiplog", "2026 ship log: Apr 17 Zaude born; Apr 29 AI product UI live with 776 tests; May 19 AtomOS v1.1 live; May 19 AI hiring POC; Jun 21 Zaude 3; Jul 06 5-model review panel; Sep 6,085 CI tests; Oct 1,750+ UltaHost commits")}

{DIV}

{pic("h-projects", "What I Build")}

{pic("projects", "Projects: AI Server-Management Assistant (UltaHost, active), Self-Hosted Supabase Platform (UltaHost, active, 6,085 CI tests), AtomOS (client, live), CommunityOS (active, 47/47 security findings fixed), AI Product UI Rebuild (UltaHost, shipped, 776 tests), Masir (live MVP)")}

<details>
<summary><b>&#129520; More builds</b></summary>

<br/>

| Project | What | Stack |
|---|---|---|
| **AI Hiring Pipeline** | Recruiting proof of concept: screened 10 CVs in 71s with zero node failures | `n8n` `Claude API` `Postgres` `Docker` |
| **FitMe** | Mobile marketplace for fitness coaches: 28 tables with RLS, ~35 screens, 119 tests | `Expo 54` `React Native` `Supabase` `PostGIS` |
| **zhost.lab** | Proxmox homelab with 14 LXC services, self-healing watchdogs, and a custom Bun + Hono ops console | `Proxmox` `LXC` `Tailscale` `Caddy` |
| **Internal DevOps Dashboard** | Real-time infrastructure control panel: 11 pages, 20+ endpoints, 15 AI ops tools | `React` `Hono` `Bun` `Claude API` |

</details>

{DIV}

{pic("h-stack", "Tech Stack")}

{pic("stack", "Tech stack: TypeScript, JavaScript, Python, React, Next.js, Vite, Tailwind, Node.js, Bun, NestJS, Prisma, PostgreSQL, Supabase, Redis, MongoDB, Docker, GitHub Actions, Nginx, Linux, Jest, Vitest, Claude Code, Playwright, n8n, Proxmox")}

{DIV}

{pic("h-work", "How I Work")}

{pic("pipeline", "How I ship: design, build, 5-model review, verify, ship")}

{pic("principles", "How I work: design first, evidence not claims, multi-model review, root-cause fixes, real data only, machine-enforced guardrails")}

{DIV}

{pic("h-activity", "GitHub Activity")}

<div align="center">

<img height="170em" src="{STREAK.format(t="github-dark-blue", bg="0d1117", ring="58a6ff")}" alt="Streak stats" />

<br/><br/>

<img src="https://raw.githubusercontent.com/ziadmomen10/ziadmomen10/output/github-snake-dark.svg" alt="Contribution snake" />

</div>

<br/>

<div align="center">

<a href="{ZAUDE}"><img src="https://custom-icon-badges.demolab.com/badge/Try-Zaude-58a6ff?style=for-the-badge&logo=rocket&logoColor=white&labelColor=161b22" /></a>&nbsp;&nbsp;
<a href="mailto:ziadmomen10@gmail.com"><img src="https://custom-icon-badges.demolab.com/badge/Gmail-ziadmomen10-EA4335?style=for-the-badge&logo=mail&logoColor=white&labelColor=161b22" /></a>

<sub><i>Private work is described at a high level. Numbers come from real CI runs and project logs.</i></sub>

{pic("footer", "Don't vibe code. Zaude code.")}

</div>
"""

(Path(__file__).parent.parent / "README.md").write_text(md, encoding="utf-8")
print("README.md written,", md.count("<picture>"), "picture elements")
